# Generated by Django 3.0.6 on 2020-05-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20200530_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
